# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x0c\x62\x61se_package\"\x1a\n\x07request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08response\x12\x0f\n\x07message\x18\x01 \x01(\t\"J\n\ractionrequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x66ile\x18\x04 \x01(\x0c\"K\n\x0e\x61\x63tionresponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x66ile\x18\x04 \x01(\x0c\x32\x96\x01\n\x08\x46ormData\x12J\n\x0buploadModel\x12\x1b.base_package.actionrequest\x1a\x1c.base_package.actionresponse\"\x00\x12>\n\x0b\x63ommunicate\x12\x15.base_package.request\x1a\x16.base_package.response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=28
  _globals['_REQUEST']._serialized_end=54
  _globals['_RESPONSE']._serialized_start=56
  _globals['_RESPONSE']._serialized_end=83
  _globals['_ACTIONREQUEST']._serialized_start=85
  _globals['_ACTIONREQUEST']._serialized_end=159
  _globals['_ACTIONRESPONSE']._serialized_start=161
  _globals['_ACTIONRESPONSE']._serialized_end=236
  _globals['_FORMDATA']._serialized_start=239
  _globals['_FORMDATA']._serialized_end=389
# @@protoc_insertion_point(module_scope)
