# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from blockchain.node.base_package.proto import data_pb2 as proto_dot_data__pb2


class FormDataStub(object):
    """定义服务,用在rpc传输中
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.uploadModel = channel.unary_unary(
                '/base_package.FormData/uploadModel',
                request_serializer=proto_dot_data__pb2.actionrequest.SerializeToString,
                response_deserializer=proto_dot_data__pb2.actionresponse.FromString,
                )
        self.communicate = channel.unary_unary(
                '/base_package.FormData/communicate',
                request_serializer=proto_dot_data__pb2.request.SerializeToString,
                response_deserializer=proto_dot_data__pb2.response.FromString,
                )


class FormDataServicer(object):
    """定义服务,用在rpc传输中
    """

    def uploadModel(self, request, context):
        """上传模型
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def communicate(self, request, context):
        """节点间交流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FormDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'uploadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.uploadModel,
                    request_deserializer=proto_dot_data__pb2.actionrequest.FromString,
                    response_serializer=proto_dot_data__pb2.actionresponse.SerializeToString,
            ),
            'communicate': grpc.unary_unary_rpc_method_handler(
                    servicer.communicate,
                    request_deserializer=proto_dot_data__pb2.request.FromString,
                    response_serializer=proto_dot_data__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'base_package.FormData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FormData(object):
    """定义服务,用在rpc传输中
    """

    @staticmethod
    def uploadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base_package.FormData/uploadModel',
            proto_dot_data__pb2.actionrequest.SerializeToString,
            proto_dot_data__pb2.actionresponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def communicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/base_package.FormData/communicate',
            proto_dot_data__pb2.request.SerializeToString,
            proto_dot_data__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
